/**
 * v1.0.5 §C — one-shot regenerator for the default topic library.
 *
 * Reads the current DB's topics table and writes BOTH:
 *   - data/topics-default.json
 *   - src/storage/migrations/007_topics_default.sql
 *
 * from a single in-memory array, so the two are physically guaranteed
 * to be in sync at generation time. Run after adding/editing topics in
 * the Web UI when you want the new defaults to ship to other hosts.
 *
 * Usage: pnpm tsx scripts/export-topics-default.ts
 *
 * Idempotent: re-running with the same DB overwrites both files with
 * identical content. The drift test (tests/storage/topics-default.test.ts)
 * catches divergence if someone hand-edits one file without the other.
 *
 * Env:
 *   DB_PATH — path to the SQLite DB (default ./data/oral-teacher.db)
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import Database from 'better-sqlite3'

interface SeedTopic {
  name: string
  keywords: string[]
  description: string
  createdAt: string
}

const DEFAULT_DB_PATH = './data/oral-teacher.db'
const JSON_PATH = './data/topics-default.json'
const SQL_PATH = './src/storage/migrations/007_topics_default.sql'

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''")
}

function main(): void {
  const dbPath = process.env.DB_PATH ?? DEFAULT_DB_PATH
  const db = new Database(dbPath, { readonly: true })

  const rows = db
    .prepare('SELECT name, keywords_json, description, created_at FROM topics ORDER BY name')
    .all() as Array<{
    name: string
    keywords_json: string
    description: string
    created_at: string
  }>
  db.close()

  if (rows.length === 0) {
    process.stderr.write(`[export] no topics in ${dbPath} — aborting\n`)
    process.exit(1)
  }

  const seeds: SeedTopic[] = rows.map((r) => ({
    name: r.name,
    keywords: JSON.parse(r.keywords_json) as string[],
    description: r.description,
    createdAt: r.created_at,
  }))

  // 1. Write JSON
  const jsonContent = `${JSON.stringify(seeds, null, 2)}\n`
  writeFileSync(JSON_PATH, jsonContent, 'utf-8')
  process.stderr.write(`[export] wrote ${seeds.length} topics to ${JSON_PATH}\n`)

  // 2. Generate SQL (same in-memory array → physical sync with JSON)
  const header = `-- 007_topics_default.sql
-- v1.0.5 §C — ship ${seeds.length} default topics as the project baseline.
-- Generated by scripts/export-topics-default.ts — DO NOT EDIT BY HAND.
-- Companion to data/topics-default.json.
-- See tests/storage/topics-default.test.ts for the drift test.
--
-- INSERT OR IGNORE makes this idempotent:
--   * Fresh install: 003 仅 CREATE TABLE, 007 seeds ${seeds.length} → ${seeds.length}
--   * Existing user with v0.6 7 (minecraft/school/.../music): 007 名字无重叠,加 ${seeds.length} → ${seeds.length + 7}
--     (用户可在 Web UI 删 7 个 v0.6 旧名;或保留)
--   * Existing user with ${seeds.length}+ (本项目基线名): OR IGNORE 全部跳过 → 用户编辑保留
--
-- Migration 003 在本 sprint 中已移除 7 条 seed,仅保留 CREATE TABLE
-- (schema_migrations 按文件名去重,旧库保留其 7 个 v0.6 话题)。

INSERT OR IGNORE INTO topics (name, keywords_json, description, created_at) VALUES
`

  const values = seeds
    .map((s) => {
      const name = sqlEscape(s.name)
      const kj = sqlEscape(JSON.stringify(s.keywords))
      const desc = sqlEscape(s.description)
      return `  ('${name}', '${kj}', '${desc}', '${s.createdAt}')`
    })
    .join(',\n')

  const sql = `${header}${values};\n`
  mkdirSync(dirname(SQL_PATH), { recursive: true })
  writeFileSync(SQL_PATH, sql, 'utf-8')
  process.stderr.write(`[export] wrote ${seeds.length} topics to ${SQL_PATH}\n`)
}

main()
