-- 007_topics_default.sql
-- v1.0.5 §C — ship 34 default topics as the project baseline.
-- Generated by scripts/export-topics-default.ts — DO NOT EDIT BY HAND.
-- Companion to data/topics-default.json.
-- See tests/storage/topics-default.test.ts for the drift test.
--
-- INSERT OR IGNORE makes this idempotent:
--   * Fresh install: 003 仅 CREATE TABLE, 007 seeds 34 → 34
--   * Existing user with v0.6 7 (minecraft/school/.../music): 007 名字无重叠,加 34 → 41
--     (用户可在 Web UI 删 7 个 v0.6 旧名;或保留)
--   * Existing user with 34+ (本项目基线名): OR IGNORE 全部跳过 → 用户编辑保留
--
-- Migration 003 在本 sprint 中已移除 7 条 seed,仅保留 CREATE TABLE
-- (schema_migrations 按文件名去重,旧库保留其 7 个 v0.6 话题)。

INSERT OR IGNORE INTO topics (name, keywords_json, description, created_at) VALUES
  ('art_culture', '["art","culture","creativity","heritage","protect","music","painting","museum","history","traditional","modern","education","important","value","expression","artist","performance","design"]', '艺术与文化 (B2)', '2026-06-14T16:39:34.703Z'),
  ('aviation', '["aviation","aircraft","airplane","plane","flying","fly","pilot","cockpit","captain","landing","takeoff","jet","flight","boeing","airbus","propeller","fly-by-wire","airport","airline","airspace","飞机","飞行","飞行员","波音","驾驶舱","客机","737","a380","dvorak","737max","737max8"]', '航空与飞行 — 飞机、驾驶舱、飞行员、波音/空客 (B2)', '2026-07-13T13:55:00.000Z'),
  ('culture_tradition', '["culture","tradition","festival","holiday","chinese","western","custom","celebrate","spring","lunar","new","year","family","traditional","different","difference","compare","special","food","gift"]', '风俗与文化 (B1)', '2026-06-14T16:39:34.702Z'),
  ('daily_routine', '["daily","routine","morning","afternoon","evening","night","wake","sleep","breakfast","lunch","dinner","bus","walk","school","home","homework","tv","watch","habit","schedule","usually","often"]', '日常生活习惯 (A1-A2)', '2026-06-14T16:39:34.699Z'),
  ('education_debate', '["education","debate","traditional","online","exam","test","score","pressure","lifelong","learning","value","degree","knowledge","skill","system","reform","compare","advantage","disadvantage"]', '教育与发展 (B2)', '2026-06-14T16:39:34.703Z'),
  ('education_learning', '["education","learning","study","school","university","college","skill","knowledge","value","important","online","course","teach","teacher","student","exam","grade","future","subject","extracurricular"]', '教育与学习 (B1)', '2026-06-14T16:39:34.702Z'),
  ('entertainment', '["movie","film","music","song","tv","show","watch","listen","favorite","actor","singer","band","star","like","book","read","game","play","video","concert","cinema","theater","netflix"]', '娱乐与媒体 (A1-A2 / B1)', '2026-06-14T16:39:34.702Z'),
  ('environment', '["environment","nature","earth","climate","weather","change","pollution","green","energy","recycle","protect","save","planet","animal","plant","tree","forest","river","sea","ocean","sustainable","eco"]', '环境与自然 (B1)', '2026-06-14T16:39:34.703Z'),
  ('experience_opinion', '["experience","opinion","think","believe","feel","remember","memory","unforgettable","proud","achievement","difficult","decision","help","change","learn","lesson","story","once","ever"]', '个人经历与观点 (B1)', '2026-06-14T16:39:34.702Z'),
  ('food_drink', '["food","eat","drink","restaurant","cook","cooking","recipe","dish","meal","breakfast","lunch","dinner","snack","fruit","vegetable","meat","rice","noodle","pizza","burger","delicious","taste","like","favorite","watermelon","summer","hot","cold"]', '饮食 (A1-A2)', '2026-06-14T16:39:34.700Z'),
  ('food_lifestyle', '["food","diet","culture","difference","healthy","fast","organic","vegetarian","vegan","cuisine","restaurant","home","cook","tradition","western","chinese","lifestyle","choice","habit"]', '食物与生活方式 (B2)', '2026-06-14T16:39:34.703Z'),
  ('friends_social', '["friend","friends","best","together","weekend","visit","play","meet","social","classmate","neighbor","describe","like","fun","often","hang","talk"]', '朋友与社交 (A1-A2)', '2026-06-14T16:39:34.700Z'),
  ('future_plans', '["future","plan","dream","job","career","want","become","travel","visit","learn","skill","study","university","hope","wish","goal","ambition","someday","later"]', '未来计划 (B1)', '2026-06-14T16:39:34.702Z'),
  ('gaming', '["game","gaming","video_game","gamer","shooter","fps","battle","tactical","multiplayer","delta_force","battlefield","minecraft","gameplay","controller","console","online","tournament","strategy","headset","bilibili","游戏","射击","战术","联机","三角洲","主机","电竞"]', '电子游戏 — 射击/Minecraft/B 站游戏主播 (A1-A2 / B1)', '2026-07-13T13:55:00.000Z'),
  ('health_exercise', '["health","healthy","exercise","sport","run","swim","walk","gym","fitness","fit","strong","eat","sleep","feel","tired","energy","practice","habit"]', '健康 (A1-A2)', '2026-06-14T16:39:34.702Z'),
  ('hobbies', '["hobby","hobbies","free","time","spare","sport","game","read","music","draw","paint","cook","computer","online","weekend","activity","fun","like","enjoy","interest","basketball","football","swim","run"]', '爱好与休闲 (A1-A2)', '2026-06-14T16:39:34.700Z'),
  ('home_family', '["home","house","apartment","room","bedroom","kitchen","living","family","live","weekend","parent","mom","dad","mother","father","grandfather","grandmother","pet","dog","cat","together","with"]', '家庭与住所 (A1-A2)', '2026-06-14T16:39:34.699Z'),
  ('media_impact', '["media","impact","influence","movie","music","book","social","internet","celebrity","famous","advertisement","ad","consumer","culture","trend","popular","fake","news","information"]', '娱乐与媒体 (B2)', '2026-06-14T16:39:34.703Z'),
  ('music', '["music","song","singer","band","album","concert","perform","melody","instrument","piano","cello","violin","orchestra","classical","folk","rock","pop","lyric","guitar","drummer","composer","conductor","rehearsal","音乐","乐队","古典","民谣","摇滚","大提琴","钢琴","乐团","演唱会","赵雷","程艾影","新裤子","痛仰","concert_hall","recital"]', '音乐 — 古典/民谣/摇滚、乐器、乐队、演唱会 (A1-A2 / B1 / B2)', '2026-07-13T13:55:00.000Z'),
  ('personal_info', '["name","age","from","live","family","brother","sister","member","introduce","where","who","hometown","birthday","old","year"]', '个人信息 (A1-A2)', '2026-06-14T16:39:34.697Z'),
  ('relationships', '["relationship","family","friend","parent","conflict","argue","get","along","understand","communication","talk","respect","care","love","trust","help","share","together","spend","time"]', '人际关系 (B1)', '2026-06-14T16:39:34.702Z'),
  ('school_life', '["school","subject","class","teacher","homework","exam","test","study","favorite","difficult","math","english","science","campus","student","classmate","grade","project","assignment","break","recess"]', '学校与学习 (A1-A2)', '2026-06-14T16:39:34.699Z'),
  ('shopping', '["shop","shopping","buy","store","mall","market","clothes","price","money","online","like","often","with","weekend","new"]', '购物 (A1-A2)', '2026-06-14T16:39:34.702Z'),
  ('society', '["society","social","friendship","value","generation","gap","community","online","face","relationship","trust","belong","network","connection","real","virtual","compare","difference"]', '人际关系与社会 (B2)', '2026-06-14T16:39:34.703Z'),
  ('space_science', '["space","moon","rocket","nasa","spacecraft","artemis","astronaut","planet","star","galaxy","biology","science","experiment","magazine","research","earth","mars","lunar","satellite","telescope","mission","orbit","太空","月球","火箭","宇宙","生物","科学"]', '太空与科学 — Artemis、月球、生物、科普杂志 (B1 / B2)', '2026-07-13T13:55:00.000Z'),
  ('sports_health_b2', '["sport","competition","versus","professional","athlete","health","mental","physical","extreme","risk","value","team","individual","fair","spirit","champion","tournament","olympic"]', '体育与健康 (B2)', '2026-06-14T16:39:34.703Z'),
  ('sustainability', '["sustainable","climate","change","carbon","footprint","recycle","waste","green","energy","solar","wind","power","lifestyle","environment","protect","action","global","warming","future"]', '环境与可持续发展 (B2)', '2026-06-14T16:39:34.703Z'),
  ('tech_future', '["future","ai","artificial","intelligence","robot","automation","digital","privacy","security","data","innovation","change","job","society","human","ethics","technology","virtual","reality"]', '科技与未来 (B2)', '2026-06-14T16:39:34.703Z'),
  ('technology', '["technology","tech","phone","mobile","computer","internet","online","social","media","app","game","gaming","video","digital","screen","time","use","life","change","future","ai","robot","smart"]', '科技与生活 (B1)', '2026-06-14T16:39:34.703Z'),
  ('travel', '["travel","trip","vacation","holiday","visit","place","city","country","beach","mountain","hiking","hike","park","nature","outdoor","summer","winter","season","photo","picture","scenery","view","hotel","flight","train","airport","bus"]', '旅行与度假 (A1-A2 / B1)', '2026-06-14T16:39:34.702Z'),
  ('travel_adventure', '["adventure","backpack","tour","solo","group","cultural","shock","adapt","eco","tourism","journey","explore","discover","abroad","foreign","language","local","experience","growth"]', '旅行与探险 (B2)', '2026-06-14T16:39:34.703Z'),
  ('weather_seasons', '["weather","season","spring","summer","autumn","winter","hot","cold","warm","cool","rain","snow","sun","wind","cloud","temperature","like","favorite","activity","feel"]', '天气与季节 (A1-A2)', '2026-06-14T16:39:34.702Z'),
  ('work_career', '["work","job","career","part","time","full","summer","intern","company","boss","colleague","salary","money","skill","experience","dream","ideal","future","balance","life"]', '工作与职业 (B1)', '2026-06-14T16:39:34.703Z'),
  ('work_life_balance', '["balance","work","life","remote","office","home","stress","manage","time","priority","leisure","vacation","overtime","burnout","wellness","happiness","satisfaction","career","choice"]', '工作与生活 (B2)', '2026-06-14T16:39:34.703Z');
