-- 007_topics_default.sql
-- v1.0.5 §C — ship 34 default topics as the project baseline.
-- Generated by scripts/export-topics-default.ts — DO NOT EDIT BY HAND.
-- Companion to data/topics-default.json.
-- See tests/storage/topics-default.test.ts for the drift test.
--
-- INSERT OR IGNORE makes this idempotent:
--   * Fresh install: 003 only runs CREATE TABLE, 007 seeds 34 → 34 total.
--   * Existing user with v0.6's 7 legacy names (minecraft/school/.../music):
--     no name overlap with 007, so 007 inserts 34 new rows → user ends up
--     with 41. They can delete the 7 legacy names via Web UI; or keep them.
--   * Existing user with 34+ baseline names: OR IGNORE skips every row,
--     preserving any user edits made since migration 003.
--
-- Migration 003 has removed its 7 legacy seed rows; it only creates the
-- table now. The schema_migrations table tracks which files have run, so
-- old installs still keep their original 7 v0.6 names.

INSERT OR IGNORE INTO topics (name, keywords_json, description, created_at) VALUES
  ('art_culture', '["art","culture","creativity","heritage","protect","music","painting","museum","history","traditional","modern","education","important","value","expression","artist","performance","design"]', 'Art & culture (B2)', '2026-06-14T16:39:34.703Z'),
  ('aviation', '["aviation","aircraft","airplane","plane","flying","fly","pilot","cockpit","captain","landing","takeoff","jet","flight","boeing","airbus","propeller","fly-by-wire","airport","airline","airspace","airliner","passenger","737","a380","dvorak","737max","737max8"]', 'Aviation & flight — airplane, cockpit, pilot, Boeing/Airbus (B2)', '2026-07-13T13:55:00.000Z'),
  ('culture_tradition', '["culture","tradition","festival","holiday","chinese","western","custom","celebrate","spring","lunar","new","year","family","traditional","different","difference","compare","special","food","gift"]', 'Customs & culture (B1)', '2026-06-14T16:39:34.702Z'),
  ('daily_routine', '["daily","routine","morning","afternoon","evening","night","wake","sleep","breakfast","lunch","dinner","bus","walk","school","home","homework","tv","watch","habit","schedule","usually","often"]', 'Daily routine (A1-A2)', '2026-06-14T16:39:34.699Z'),
  ('education_debate', '["education","debate","traditional","online","exam","test","score","pressure","lifelong","learning","value","degree","knowledge","skill","system","reform","compare","advantage","disadvantage"]', 'Education & development (B2)', '2026-06-14T16:39:34.703Z'),
  ('education_learning', '["education","learning","study","school","university","college","skill","knowledge","value","important","online","course","teach","teacher","student","exam","grade","future","subject","extracurricular"]', 'Education & learning (B1)', '2026-06-14T16:39:34.702Z'),
  ('entertainment', '["movie","film","music","song","tv","show","watch","listen","favorite","actor","singer","band","star","like","book","read","game","play","video","concert","cinema","theater","netflix"]', 'Entertainment & media (A1-A2 / B1)', '2026-06-14T16:39:34.702Z'),
  ('environment', '["environment","nature","earth","climate","weather","change","pollution","green","energy","recycle","protect","save","planet","animal","plant","tree","forest","river","sea","ocean","sustainable","eco"]', 'Environment & nature (B1)', '2026-06-14T16:39:34.703Z'),
  ('experience_opinion', '["experience","opinion","think","believe","feel","remember","memory","unforgettable","proud","achievement","difficult","decision","help","change","learn","lesson","story","once","ever"]', 'Personal experience & opinion (B1)', '2026-06-14T16:39:34.702Z'),
  ('food_drink', '["food","eat","drink","restaurant","cook","cooking","recipe","dish","meal","breakfast","lunch","dinner","snack","fruit","vegetable","meat","rice","noodle","pizza","burger","delicious","taste","like","favorite","watermelon","summer","hot","cold"]', 'Food & drink (A1-A2)', '2026-06-14T16:39:34.700Z'),
  ('food_lifestyle', '["food","diet","culture","difference","healthy","fast","organic","vegetarian","vegan","cuisine","restaurant","home","cook","tradition","western","chinese","lifestyle","choice","habit"]', 'Food & lifestyle (B2)', '2026-06-14T16:39:34.703Z'),
  ('friends_social', '["friend","friends","best","together","weekend","visit","play","meet","social","classmate","neighbor","describe","like","fun","often","hang","talk"]', 'Friends & social life (A1-A2)', '2026-06-14T16:39:34.700Z'),
  ('future_plans', '["future","plan","dream","job","career","want","become","travel","visit","learn","skill","study","university","hope","wish","goal","ambition","someday","later"]', 'Future plans (B1)', '2026-06-14T16:39:34.702Z'),
  ('gaming', '["game","gaming","video_game","gamer","shooter","fps","battle","tactical","multiplayer","delta_force","battlefield","minecraft","gameplay","controller","console","online","tournament","strategy","headset","bilibili","videogame","esports","streamer"]', 'Video games — shooters, Minecraft, Bilibili gaming streamers (A1-A2 / B1)', '2026-07-13T13:55:00.000Z'),
  ('health_exercise', '["health","healthy","exercise","sport","run","swim","walk","gym","fitness","fit","strong","eat","sleep","feel","tired","energy","practice","habit"]', 'Health & exercise (A1-A2)', '2026-06-14T16:39:34.702Z'),
  ('hobbies', '["hobby","hobbies","free","time","spare","sport","game","read","music","draw","paint","cook","computer","online","weekend","activity","fun","like","enjoy","interest","basketball","football","swim","run"]', 'Hobbies & leisure (A1-A2)', '2026-06-14T16:39:34.700Z'),
  ('home_family', '["home","house","apartment","room","bedroom","kitchen","living","family","live","weekend","parent","mom","dad","mother","father","grandfather","grandmother","pet","dog","cat","together","with"]', 'Home & family (A1-A2)', '2026-06-14T16:39:34.699Z'),
  ('media_impact', '["media","impact","influence","movie","music","book","social","internet","celebrity","famous","advertisement","ad","consumer","culture","trend","popular","fake","news","information"]', 'Media impact (B2)', '2026-06-14T16:39:34.703Z'),
  ('music', '["music","song","singer","band","album","concert","perform","melody","instrument","piano","cello","violin","orchestra","classical","folk","rock","pop","lyric","guitar","drummer","composer","conductor","rehearsal","concert_hall","recital","zhaolei","chengaiying","newpants","tongyang","livemusic"]', 'Music — classical, folk, rock, instruments, bands, concerts (A1-A2 / B1 / B2)', '2026-07-13T13:55:00.000Z'),
  ('personal_info', '["name","age","from","live","family","brother","sister","member","introduce","where","who","hometown","birthday","old","year"]', 'Personal info (A1-A2)', '2026-06-14T16:39:34.697Z'),
  ('relationships', '["relationship","family","friend","parent","conflict","argue","get","along","understand","communication","talk","respect","care","love","trust","help","share","together","spend","time"]', 'Relationships (B1)', '2026-06-14T16:39:34.702Z'),
  ('school_life', '["school","subject","class","teacher","homework","exam","test","study","favorite","difficult","math","english","science","campus","student","classmate","grade","project","assignment","break","recess"]', 'School life (A1-A2)', '2026-06-14T16:39:34.699Z'),
  ('shopping', '["shop","shopping","buy","store","mall","market","clothes","price","money","online","like","often","with","weekend","new"]', 'Shopping (A1-A2)', '2026-06-14T16:39:34.702Z'),
  ('society', '["society","social","friendship","value","generation","gap","community","online","face","relationship","trust","belong","network","connection","real","virtual","compare","difference"]', 'Society & relationships (B2)', '2026-06-14T16:39:34.703Z'),
  ('space_science', '["space","moon","rocket","nasa","spacecraft","artemis","astronaut","planet","star","galaxy","biology","science","experiment","magazine","research","earth","mars","lunar","satellite","telescope","mission","orbit","cosmos","sciencemag"]', 'Space & science — Artemis, Moon, biology, science magazines (B1 / B2)', '2026-07-13T13:55:00.000Z'),
  ('sports_health_b2', '["sport","competition","versus","professional","athlete","health","mental","physical","extreme","risk","value","team","individual","fair","spirit","champion","tournament","olympic"]', 'Sports & health (B2)', '2026-06-14T16:39:34.703Z'),
  ('sustainability', '["sustainable","climate","change","carbon","footprint","recycle","waste","green","energy","solar","wind","power","lifestyle","environment","protect","action","global","warming","future"]', 'Environment & sustainability (B2)', '2026-06-14T16:39:34.703Z'),
  ('tech_future', '["future","ai","artificial","intelligence","robot","automation","digital","privacy","security","data","innovation","change","job","society","human","ethics","technology","virtual","reality"]', 'Tech & future (B2)', '2026-06-14T16:39:34.703Z'),
  ('technology', '["technology","tech","phone","mobile","computer","internet","online","social","media","app","game","gaming","video","digital","screen","time","use","life","change","future","ai","robot","smart"]', 'Technology & life (B1)', '2026-06-14T16:39:34.703Z'),
  ('travel', '["travel","trip","vacation","holiday","visit","place","city","country","beach","mountain","hiking","hike","park","nature","outdoor","summer","winter","season","photo","picture","scenery","view","hotel","flight","train","airport","bus"]', 'Travel & vacation (A1-A2 / B1)', '2026-06-14T16:39:34.702Z'),
  ('travel_adventure', '["adventure","backpack","tour","solo","group","cultural","shock","adapt","eco","tourism","journey","explore","discover","abroad","foreign","language","local","experience","growth"]', 'Travel & adventure (B2)', '2026-06-14T16:39:34.703Z'),
  ('weather_seasons', '["weather","season","spring","summer","autumn","winter","hot","cold","warm","cool","rain","snow","sun","wind","cloud","temperature","like","favorite","activity","feel"]', 'Weather & seasons (A1-A2)', '2026-06-14T16:39:34.702Z'),
  ('work_career', '["work","job","career","part","time","full","summer","intern","company","boss","colleague","salary","money","skill","experience","dream","ideal","future","balance","life"]', 'Work & career (B1)', '2026-06-14T16:39:34.703Z'),
  ('work_life_balance', '["balance","work","life","remote","office","home","stress","manage","time","priority","leisure","vacation","overtime","burnout","wellness","happiness","satisfaction","career","choice"]', 'Work-life balance (B2)', '2026-06-14T16:39:34.703Z');
